image: python:3.9

stages:
  - lint
  - test
  - types
  - release

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Python Code Lint:
  stage: lint
  before_script: []
  script:
    - pip install -r requirements-cicd.txt
    - black sqlalchemy_wrapper tests
    - mypy sqlalchemy_wrapper --ignore-missing-imports

Unit Tests:
  stage: test
  script:
    - poetry run pytest

Release:
  stage: release
  script:
    - pip install python-semantic-release
    - export REPOSITORY_URL="https://code-repo.cloudmali.ml/api/v4/projects/$PROJECT_ID/packages/pypi"
    - export REPOSITORY_USERNAME=admin
    - export REPOSITORY_PASSWORD=$REGISTRY_TOKEN
    - semantic-release print-version
    - semantic-release publish
  only:
    - main
  artifacts:
    name: sqlalchemy_wrapper_files
    paths:
        - dist/*